image: maven:latest

variables:
  SOME_VAR: "some value"
  SONAR_TOKEN: $SONAR_TOKEN

stages:
  - test
  # - build
  # - sonarqube
  # - deploy

before_script:
  - echo "Start CI/CD"
  - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  - echo $CI_JOB_STAGE  # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

# build:
#   image: maven:latest
#   stage: build
#   script:
#     - echo "Build process"
#     - mvn clean package -Dmaven.test.skip=true
#     - echo "Build ok"
#   only:
#     - master
#   tags:
#     - Cuddle runner

# unittest:
#   stage: test
#   script:
#     - echo "start test"
#     #- mvn clean package
#     - echo "test ok"
#   only:
#     - master
#   tags:
#     - Cuddle runner

katalon_test_suite:
  image: katalonstudio/katalon:latest
  stage: test
  script:
    - echo "start katalon test suite"
    - docker-compose down --rmi all
    - katalonc -runMode=console -projectPath=$(pwd) -testSuitePath=Cuddle -browserType=Chrome
    - docker-compose up -d --build
    - echo "katalon test suite ok"
  only:
    - master
  tags:
    - Cuddle runner

# sonarqube:
#   image: maven:latest
#   stage: sonarqube
#   script:
#     - echo "start sonarqube stage"
#     - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
#     - echo "Wow, code is so clean!"
#     - echo "sonarqube ok"
#   only:
#     - master
#   tags:
#     - Cuddle runner

deploy_ssh:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy apps"
    - docker-compose down --rmi all
    - docker-compose up -d --build
    - echo "deploy ok"
  only:
    - master
  tags:
    - Cuddle runner
  when: manual

after_script:
  - echo "End CI/CD"