image: maven:latest

variables:
  SOME_VAR: "some value"

stages:
  - build
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"
  - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  - echo $CI_JOB_STAGE  # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

build:
  image: maven:latest
  stage: build
  script:
    - echo "Build process"
    - mvn clean package -Dmaven.test.skip=true
    - echo "Build ok"
  only:
    - master
  tags:
    - Cuddle runner

unittest:
  stage: test
  script:
    - echo "start test"
    - mvn clean package
    - echo "test ok"
  only:
    - master
  tags:
    - Cuddle runner

katalon_test_suite:
  stage: test
  script:
    - echo "start katalon test suite"
    - echo "katalon test suite ok"
  only:
    - master
  tags:
    - Cuddle runner

sonarqube:
  image: maven:latest
  stage: sonarqube
  script:
    - echo "start sonarqube stage"
    #- mvn clean package sonar:sonar\​
    #  -Dsonar.projectKey=$SONARQUBE_PROJECT_KEY\​
    #  -Dsonar.host.url=$SONARQUBE_URL\​
    #  -Dsonar.login=$SONARQUBE_LOGIN_KEY
    - echo "Wow, code is so clean!"
    - echo "sonarqube ok"
  only:
    - master
  tags:
    - Cuddle runner

deploy_ssh:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy apps"
    - docker-compose down
    - docker-compose up -d
    - echo "deploy ok"
  only:
    - master
  tags:
    - Cuddle runner
  when: manual

after_script:
  - echo "End CI/CD"